# Generated by Django 4.0.4 on 2022-05-28 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertorModelForEverything',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('popularity', models.BigIntegerField()),
                ('duration_ms', models.BigIntegerField()),
                ('explicit', models.BigIntegerField()),
                ('artists', models.CharField(max_length=1000)),
                ('id_artists', models.CharField(max_length=1000)),
                ('release_date', models.CharField(max_length=1000)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.BigIntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.BigIntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.BigIntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_f1', models.URLField()),
                ('image_f2', models.URLField()),
                ('songplay_f1', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('popularity', models.BigIntegerField()),
                ('duration_ms', models.BigIntegerField()),
                ('explicit', models.BigIntegerField()),
                ('artists', models.CharField(max_length=1000)),
                ('id_artists', models.CharField(max_length=1000)),
                ('release_date', models.CharField(max_length=1000)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.BigIntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.BigIntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('Listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.tracks')),
            ],
        ),
    ]
